[versions]
agp = "8.5.2"
circleimageview = "3.1.0"
cloudinaryAndroid = "3.0.2"
compiler = "4.16.0"
firebaseBom = "34.8.0"
glide = "4.16.0"
junit = "4.13.2"
junitVersion = "1.3.0"
espressoCore = "3.7.0"
appcompat = "1.7.1"
material = "1.13.0"
activity = "1.9.0"
constraintlayout = "2.2.1"
firebaseAuth = "24.0.1"
firebaseFirestore = "26.1.0"
monitor = "1.8.0"
okhttp = "4.12.0"
photoview = "2.3.0"
soloader = "0.12.1"
viewpager2 = "1.1.0"
volley = "1.2.1"

[libraries]
circleimageview = { module = "de.hdodenhof:circleimageview", version.ref = "circleimageview" }
cloudinary-android = { module = "com.cloudinary:cloudinary-android", version.ref = "cloudinaryAndroid" }
compiler = { module = "com.github.bumptech.glide:compiler", version.ref = "compiler" }
firebase-analytics = { module = "com.google.firebase:firebase-analytics" }
firebase-bom = { module = "com.google.firebase:firebase-bom", version.ref = "firebaseBom" }
firebase-messaging = { module = "com.google.firebase:firebase-messaging" }
glide = { module = "com.github.bumptech.glide:glide", version.ref = "glide" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
ext-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
activity = { group = "androidx.activity", name = "activity", version.ref = "activity" }
constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "constraintlayout" }
firebase-auth = { group = "com.google.firebase", name = "firebase-auth", version.ref = "firebaseAuth" }
firebase-firestore = { group = "com.google.firebase", name = "firebase-firestore", version.ref = "firebaseFirestore" }
monitor = { group = "androidx.test", name = "monitor", version.ref = "monitor" }
okhttp = { module = "com.squareup.okhttp3:okhttp", version.ref = "okhttp" }
photoview = { module = "com.github.chrisbanes:PhotoView", version.ref = "photoview" }
soloader = { module = "com.facebook.soloader:soloader", version.ref = "soloader" }
viewpager2 = { module = "androidx.viewpager2:viewpager2", version.ref = "viewpager2" }
volley = { module = "com.android.volley:volley", version.ref = "volley" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }

